### PR TITLE
Configure nanopi neo compatible toolchain

### PR DESCRIPTION
**Pull request by magnetised**
working with kernel 3.4 and gcc 4.9

### CODE REVIEW

**Comment by magnetised** [comment]
sorry, accident!

**Comment by fhunleth** [comment]
No worries - please note that we now manage toolchains in https://github.com/nerves-project/toolchains/. We've been keeping this repository around for people using old versions of Nerves.

**Comment by magnetised** [comment]
@fhunleth thanks. Am in process of creating a specific top-level toolchain package to host the binary download here: https://github.com/strobe-audio/nerves_toolchain_arm_unknown_linux_gnueabihf

Tricky to override the toolchain URL...

**Comment by fhunleth** [comment]
Does the NanoPi not support a newer Linux kernel than 3.4? That's a pretty ancient kernel and may come back to cause frustration in the future. Anyway, I'm trying to save you from having to make a custom crosscompiler. As for the toolchain URL, that's specified in `nerves_defconfig` and `nerves.exs` in the system.

**Comment by mobileoverlord** [comment]
upstream BR has nanopi at 4.10
https://github.com/buildroot/buildroot/blob/master/configs/nanopi_neo_defconfig#L16

**Comment by magnetised** [comment]
@fhunleth @mobileoverlord I'm trying to get the Friendly arm TI5102A powered DAC  to work[1] -- the only kernel tree that has support is the 'H3 Lichee' one provided by FriendlyARM (https://github.com/friendlyarm/h3_lichee). so yes, I'm stuck on 3.4 unfortunately.

I got the thing booting etc and seems to recognise the DAC but the kernel crashes if I try to use the damn thing. Still, who said it was going to be easy, huh.

[1]: http://www.friendlyarm.com/index.php?route=product/product&product_id=169

**Pull request closed without merging**
